# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films_name', models.CharField(max_length=200)),
                ('is_censored', models.NullBooleanField()),
                ('designation', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200)),
                ('series_belong_to', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name_1', models.CharField(max_length=200)),
                ('star_name_2', models.CharField(default='NoFind', max_length=200)),
                ('star_name_3', models.CharField(default='NoFind', max_length=200)),
                ('star_name_4', models.CharField(default='NoFind', max_length=200)),
                ('star_English_Name', models.CharField(default='NoFind', max_length=200)),
                ('age_group', models.CharField(default='NoSet', max_length=200)),
                ('star_rank', models.CharField(default='NoSet', max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_film_with_series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADP.Film')),
                ('series_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADP.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Table_film_with_star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADP.Film')),
                ('star_name_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADP.Star')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADP.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='Series_connect',
            field=models.ManyToManyField(through='ADP.Table_film_with_series', to='ADP.Series'),
        ),
        migrations.AddField(
            model_name='film',
            name='stars_connect',
            field=models.ManyToManyField(through='ADP.Table_film_with_star', to='ADP.Star'),
        ),
    ]
